# Generated by Django 4.0.6 on 2022-08-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_posts_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='timestamp',
            new_name='created',
        ),
    ]
