# Generated by Django 4.0.6 on 2022-08-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_timestamp_posts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
